### ISSUE TITLE
error selinux @ file:///builddir/build/BUILD/libselinux-3.5/src What is this?

### ISSUE THREAD

**Issue by Roboxkin** [ImSreyas/OCR-wizard#2]
what are these lines and why are they needed in requirements.txt

error selinux @ file:///builddir/build/BUILD/libselinux-3.5/src
error sepolicy @ file:///builddir/build/BUILD/selinux-3.5/python/sepolicy

**Comment by ImSreyas** [comment]
Its some Linux dependencies, safe to remove if you are on a windows platform 😀.
